### ISSUE TITLE
Floating point values on Windows 10 with german locale settings

### ISSUE THREAD

**Issue by mayerrobert** [kimtg/Closhure#2]
It seems that Closhure gets confused with decimal separators and commas on a German Windows installation where ',' is the decimal separator:

Entering "1.0" doesn't work, "1,0" seems to be read as two forms, floating point numbers are written written with a ',' as a decimal separator, though. See the REPL transcript below:

C:\robert\Closhure\bin\Debug>Closhure.exe
Closhure 0.6
Special forms:
 . and catch def defmacro do doseq finally fn if import let loop new or quasiquote quote recur reify set! try unquote unquote-splicing
Defined symbols:
 - * *command-line-args* / + < <= = == > >= apply eval filter fold gensym instance? list load-file load-string macroexpand map mod nil? not not= nth pr print println prn quot range read read-line read-string slurp spit str symbol type
Macros:
 defn dotimes when while
> 1.0
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   bei System.Double.Parse(String s)
   bei Closhure.Core.parse(TextReader r, String tok) in c:\robert\Closhure\Core.cs:Zeile 1525.
   bei Closhure.Core.parse(TextReader r) in c:\robert\Closhure\Core.cs:Zeile 1433.
   bei Closhure.Core.repl() in c:\robert\Closhure\Core.cs:Zeile 1138.
> 1,0
1
> 0
> (/ 1 3)
0,333333333333333
>

**Comment by kimtg** [comment]
Thank you for reporting this problem. Thanks to you, I solved it using System.Globalization.CultureInfo.InvariantCulture.

See: https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?view=net-7.0#system-globalization-cultureinfo-currentculture

**Comment by mayerrobert** [comment]
Great, it works now.

And thanks for the link to the .NET documentation.
